# .coderabbit.yaml
language: "en-US"

reviews:
  profile: assertive          # Thorough reviews for a backend/AI project like yours
  request_changes_workflow: true   # CodeRabbit formally "Requests Changes" on issues
                                   # and auto-approves once all comments are resolved
  high_level_summary: true
  poem: false                 # Optional: disable the poem in walkthrough
  auto_pause_after_reviewed_commits: 0  # Don't pause reviews after 5 commits

  path_instructions:
    - path: "**/*.ts"
      instructions: "Review for proper async/await handling, error propagation, and TypeScript strict typing."
    - path: "**/*.py"
      instructions: "Check for proper exception handling, type hints, and PEP8 compliance."
