# .coderabbit.yaml
language: "en-US"

reviews:
  profile: "assertive"
  request_changes_workflow: true   # ← This makes CR "Request Changes" and AUTO-APPROVE once resolved
  high_level_summary: true
  review_status: true
  poem: false
  auto_pause_after_reviewed_commits: 0  # Disable auto-pause

  auto_review:              # ← THIS was missing from your nested reviews block
    enabled: true
    auto_incremental_review: true   # Re-reviews on every new push
    drafts: false

  path_instructions:
    - path: "**/*.ts"
      instructions: "Review for proper async/await handling, error propagation, and TypeScript strict typing."
    - path: "**/*.py"
      instructions: "Check for proper exception handling, type hints, and PEP8 compliance."

chat:
  auto_reply: true
